about:
    home: https://github.com/genome/breakdancer
    license: GPLv3
    summary: SV detection from paired end reads mapping

package:
    name: breakdancer
    version: 1.4.5

build:
    skip: True  # [not py27]

requirements:
    build:
        - python >=2.7,<3
        - perl
        - cmake >=2.8
        - gcc
        - zlib
    run:
        - libgcc
        - perl-math-cdf
        - perl-statistics-descriptive

test:
    commands:
        - 'breakdancer-max 2>&1 | grep "Usage: breakdancer-max" > /dev/null'

source:
  fn: v1.4.5.tar.gz
  url: https://github.com/genome/breakdancer/archive/v1.4.5.tar.gz
  md5: 3a3fcb3731b0d9e0573c528bdcaeb18b
